### ISSUE TITLE
How to pass configFile param ?

### ISSUE THREAD

**Issue by mithuns** [hazendaz/build-tools#4]
I want to know , how I can pass in the configFile param, since its not being set anywhere ? Or if I am missing something ? 
I want to be able to set a specific config file.

**Comment by hazendaz** [comment]
@mithuns I assume you meant this as a question against formatter-maven-plugin?  If you look in that source, it is defaulted if you don't tell it in a pom where to look.  For a jar usage, you would need it in simliar location as this project provides.  If you look at [here](https://github.com/mybatis/parent) inside that pom it will provide you a better idea of how it is used in the wild.  Personally I always create a JAR containing configuration I want and let the formatter use that JAR to find the confguration so I don't copy it all over the place.

**Comment by mithuns** [comment]
True, I think I overlooked the config, I was able to find it
[MultiModule-Config](http://code.revelc.net/formatter-maven-plugin/examples.html)
, by how the dependency project was structured. Thanks anyways.

**Comment by hazendaz** [comment]
Sure anytime.  Glad you got it all figured out!  I love this project in general.  If we could get other things formatting as nicely one day that would be pretty awesome.  Currently it is heavily tilted towards java but handles javascript and json pretty well.  It's not so good with css or xml unfortunately but at least some code was introduced recently that is making an attempt at figuring that out.
